<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Driver extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'license_plate'
    ];

    /**
     * Get all transactions for the driver
     */
    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Calculate total distance traveled by this driver
     */
    public function getTotalDistanceAttribute(): int
    {
        return $this->transactions->sum(function ($transaction) {
            // Pastikan relasi rute dimuat dan ada
            if ($transaction->relationLoaded('rute') && $transaction->rute) {
                return $transaction->rute->distance;
            }
            return 0;
        });
    }

    /**
     * Calculate total cost generated by this driver
     */
    public function getTotalCostAttribute(): int
    {
        return $this->transactions->sum('total_cost');
    }

    /**
     * Calculate total late minutes by this driver
     */
    public function getTotalLateAttribute(): int
    {
        return $this->transactions->sum('late');
    }
}
